#!/usr/bin/env python3
"""
gen_web_ui.py — Embed the Scribit web UI into the firmware as PROGMEM byte arrays.

Reads web assets (html/js/css/...) from the firmware `data/` folder and writes a
single C header (`web_ui.h`) that the ESP32 firmware serves directly from flash,
so the web UI no longer depends on a SPIFFS image being deployed.

Usage:
    python tools/gen_web_ui.py
    python tools/gen_web_ui.py --data <dir> --out <web_ui.h>

Re-run this whenever you change anything in data/ (index.html, app.js, style.css),
then rebuild + reflash the ESP32 firmware.
"""
import argparse
import gzip
import os
import sys

# Only these extensions are embedded. g-code samples are intentionally excluded
# (they are large and not needed for the UI to load).
CONTENT_TYPES = {
    ".html": "text/html",
    ".htm":  "text/html",
    ".js":   "application/javascript",
    ".css":  "text/css",
    ".json": "application/json",
    ".svg":  "image/svg+xml",
    ".ico":  "image/x-icon",
    ".png":  "image/png",
    ".jpg":  "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif":  "image/gif",
}

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DATA = os.path.join(REPO_ROOT, "Firmware", "ScribitESP", "data")
DEFAULT_OUT = os.path.join(REPO_ROOT, "Firmware", "ScribitESP", "web_ui.h")


def sanitize(name: str) -> str:
    """Turn a filename into a valid C identifier fragment."""
    out = []
    for ch in name:
        out.append(ch if (ch.isalnum() or ch == "_") else "_")
    ident = "".join(out)
    if ident and ident[0].isdigit():
        ident = "_" + ident
    return ident


def emit_array(var: str, data: bytes) -> str:
    lines = [f"static const uint8_t {var}[] PROGMEM = {{"]
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02x},")
        if len(row) == 16:
            lines.append("  " + "".join(row))
            row = []
    if row:
        lines.append("  " + "".join(row))
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default=DEFAULT_DATA, help="folder with web assets")
    ap.add_argument("--out", default=DEFAULT_OUT, help="output header path")
    args = ap.parse_args()

    data_dir = os.path.abspath(args.data)
    out_path = os.path.abspath(args.out)

    if not os.path.isdir(data_dir):
        print(f"ERROR: data dir not found: {data_dir}", file=sys.stderr)
        return 1

    files = []
    for name in sorted(os.listdir(data_dir)):
        full = os.path.join(data_dir, name)
        if not os.path.isfile(full):
            continue
        ext = os.path.splitext(name)[1].lower()
        if ext not in CONTENT_TYPES:
            continue  # skip g-code and anything non-web
        files.append((name, full, CONTENT_TYPES[ext]))

    if not files:
        print(f"ERROR: no embeddable web assets found in {data_dir}", file=sys.stderr)
        return 1

    out = []
    out.append("// AUTO-GENERATED by tools/gen_web_ui.py - DO NOT EDIT BY HAND.")
    out.append("// Re-run the generator after editing files in data/, then rebuild + reflash.")
    out.append("#pragma once")
    out.append("#include <Arduino.h>")
    out.append("#include <pgmspace.h>")
    out.append("#include <string.h>")
    out.append("")
    out.append("struct EmbeddedFile {")
    out.append("  const char *path;        // request path, e.g. \"/index.html\"")
    out.append("  const uint8_t *data;     // bytes in PROGMEM (gzip-compressed when gz==1)")
    out.append("  size_t len;              // stored byte count (compressed size when gz==1)")
    out.append("  const char *contentType;")
    out.append("  uint8_t gz;              // 1 => served with Content-Encoding: gzip")
    out.append("};")
    out.append("")

    table = []
    total = 0
    total_raw = 0
    for name, full, ct in files:
        with open(full, "rb") as f:
            data = f.read()
        raw_len = len(data)
        total_raw += raw_len
        # gzip-compress; only keep it if it actually shrinks the asset.
        gzdata = gzip.compress(data, 9)
        if len(gzdata) < raw_len:
            data = gzdata
            gz = 1
        else:
            gz = 0
        total += len(data)
        var = "EMB_" + sanitize(name)
        out.append(f"// {name}  ({raw_len} bytes raw -> {len(data)} stored, gz={gz}, {ct})")
        out.append(emit_array(var, data))
        out.append("")
        req_path = "/" + name
        table.append(f'  {{ "{req_path}", {var}, sizeof({var}), "{ct}", {gz} }},')

    out.append("static const EmbeddedFile EMBEDDED_FILES[] = {")
    out.extend(table)
    out.append("};")
    out.append("static const size_t EMBEDDED_FILES_COUNT = sizeof(EMBEDDED_FILES) / sizeof(EMBEDDED_FILES[0]);")
    out.append("")
    out.append("// Returns the embedded file for a request path, or nullptr if not embedded.")
    out.append("inline const EmbeddedFile *findEmbeddedFile(const char *path) {")
    out.append("  for (size_t i = 0; i < EMBEDDED_FILES_COUNT; i++) {")
    out.append("    if (strcmp(path, EMBEDDED_FILES[i].path) == 0) return &EMBEDDED_FILES[i];")
    out.append("  }")
    out.append("  return nullptr;")
    out.append("}")
    out.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(out))

    print(f"Wrote {out_path}")
    print(f"Embedded {len(files)} files: {total_raw} bytes raw -> {total} bytes stored "
          f"(saved {total_raw - total} bytes, {100*(total_raw-total)//max(1,total_raw)}%):")
    for name, _, ct in files:
        print(f"  /{name}  ({ct})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
